In [160]:
from pymongo import MongoClient
import pandas as pd
import re
import requests


client = MongoClient('mongodb://localhost:27017/')
db = client.company

In [161]:
#filter companies that have coordinates

query= db.company.find({
    "$and":
    [{"offices.longitude":{"$exists":True}},
     {"offices.latitude":{"$ne":"null"}},
     {"offices.longitude":{"$ne":None}},
     {"offices.longitude":{"$exists":True}
     }
    ]
}
)

In [162]:
query

In [163]:
with_coords = pd.DataFrame(query)
with_coords.head(2)

,_id,acquisition,acquisitions,alias_list,blog_feed_url,blog_url,category_code,competitions,created_at,crunchbase_url,...,phone_number,products,providerships,relationships,screenshots,tag_list,total_money_raised,twitter_username,updated_at,video_embeds
0,52cdef7c4bab8bd675297d8a,"{'price_amount': 30000000, 'price_currency_cod...",[],,http://digitalquarters.net/feed/,http://digitalquarters.net/,web,"[{'competitor': {'name': 'Wikia', 'permalink':...",2007-05-25 06:51:27,http://www.crunchbase.com/company/wetpaint,...,206.859.6300,"[{'name': 'Wikison Wetpaint', 'permalink': 'we...",[],"[{'is_past': False, 'title': 'Co-Founder and V...","[{'available_sizes': [[[150, 86], 'assets/imag...","wiki, seattle, elowitz, media-industry, media-...",$39.8M,BachelrWetpaint,Sun Dec 08 07:15:44 UTC 2013,[]
1,52cdef7c4bab8bd675297d8b,None,[],Zoho ManageEngine,,,enterprise,[],2007-05-25 19:24:22,http://www.crunchbase.com/company/adventnet,...,925-924-9500,[],"[{'title': 'DHFH', 'is_past': True, 'provider'...","[{'is_past': True, 'title': 'CEO and Co-Founde...","[{'available_sizes': [[[150, 94], 'assets/imag...",,$0,manageengine,Wed Oct 31 18:26:09 UTC 2012,[]

In [164]:
with_coords.columns

Index(['_id', 'acquisition', 'acquisitions', 'alias_list', 'blog_feed_url',
       'blog_url', 'category_code', 'competitions', 'created_at',
       'crunchbase_url', 'deadpooled_day', 'deadpooled_month',
       'deadpooled_url', 'deadpooled_year', 'description', 'email_address',
       'external_links', 'founded_day', 'founded_month', 'founded_year',
       'funding_rounds', 'homepage_url', 'image', 'investments', 'ipo',
       'milestones', 'name', 'number_of_employees', 'offices', 'overview',
       'partners', 'permalink', 'phone_number', 'products', 'providerships',
       'relationships', 'screenshots', 'tag_list', 'total_money_raised',
       'twitter_username', 'updated_at', 'video_embeds'],
      dtype='object')

In [165]:
#new dataframe with filtered columns

with_coords2 = with_coords [['_id','name','number_of_employees','category_code','offices','founded_year','ipo','funding_rounds','total_money_raised','investments','deadpooled_year','partners']]
with_coords2.head(400)

,_id,name,number_of_employees,category_code,offices,founded_year,ipo,funding_rounds,total_money_raised,investments,deadpooled_year,partners
0,52cdef7c4bab8bd675297d8a,Wetpaint,47.0,web,"[{'description': '', 'address1': '710 - 2nd Av...",2005.0,NaN,"[{'id': 888, 'round_code': 'a', 'source_url': ...",$39.8M,[],1.0,[]
1,52cdef7c4bab8bd675297d8b,AdventNet,600.0,enterprise,"[{'description': 'Headquarters', 'address1': '...",1996.0,NaN,[],$0,[],2.0,[]
2,52cdef7c4bab8bd675297d8c,Zoho,1600.0,software,"[{'description': 'Headquarters', 'address1': '...",2005.0,NaN,[],$0,[],3.0,[]
3,52cdef7c4bab8bd675297d8d,Digg,60.0,news,"[{'description': None, 'address1': '135 Missis...",2004.0,None,"[{'id': 1, 'round_code': 'b', 'source_url': 'h...",$45M,[],NaN,[]
4,52cdef7c4bab8bd675297d8e,Facebook,5299.0,social,"[{'description': 'Headquarters', 'address1': '...",2004.0,"{'valuation_amount': 104000000000, 'valuation_...","[{'id': 2, 'round_code': 'angel', 'source_url'...",$2.43B,"[{'funding_round': {'round_code': 'seed', 'sou...",NaN,[]
5,52cdef7c4bab8bd675297d90,Postini,NaN,web,"[{'description': None, 'address1': '959 Skyway...",1999.0,None,[],$0,[],NaN,[]
6,52cdef7c4bab8bd675297d91,Geni,18.0,web,"[{'description': 'Headquarters', 'address1': '...",2006.0,None,"[{'id': 6, 'round_code': 'a', 'source_url': ''...",$16.5M,[],NaN,[]
7,52cdef7c4bab8bd675297d92,Flektor,NaN,games_video,"[{'description': None, 'address1': '8536 Natio...",NaN,None,[],$0,[],NaN,[]
8,52cdef7c4bab8bd675297d93,Fox Interactive Media,0.0,web,"[{'description': '', 'address1': '407 N Maple ...",1979.0,None,[],$0,"[{'funding_round': {'round_code': 'b', 'source...",NaN,[]
9,52cdef7c4bab8bd675297d94,Twitter,1300.0,social,"[{'description': '', 'address1': '1355 Market ...",2006.0,"{'valuation_amount': 18100000000, 'valuation_c...","[{'id': 261, 'round_code': 'a', 'source_url': ...",$1.16B,[],NaN,[]
10,52cdef7c4bab8bd675297d96,Gizmoz,NaN,web,"[{'description': None, 'address1': None, 'addr...",2003.0,None,"[{'id': 9, 'round_code': 'a', 'source_url': 'h...",$18.1M,[],NaN,[]
11,52cdef7c4bab8bd675297d97,Scribd,50.0,news,"[{'description': 'HQ', 'address1': '539 Bryant...",2007.0,None,"[{'id': 10, 'round_code': 'seed', 'source_url'...",$25.8M,[],NaN,[]
12,52cdef7c4bab8bd675297d98,Slacker,NaN,music,"[{'description': '', 'address1': '16935 W. Ber...",2006.0,None,"[{'id': 12, 'round_code': 'b', 'source_url': '...",$73.1M,[],NaN,[]
13,52cdef7c4bab8bd675297d99,Lala,NaN,games_video,"[{'description': 'Lala Headquarters', 'address...",NaN,None,"[{'id': 16, 'round_code': 'b', 'source_url': '...",$44.2M,[],NaN,[]
14,52cdef7c4bab8bd675297d9a,Helio,NaN,mobile,"[{'description': None, 'address1': '10960 Wils...",2005.0,None,[],$0,[],NaN,[]
15,52cdef7c4bab8bd675297d9b,eBay,15000.0,web,"[{'description': 'Headquarters', 'address1': '...",1995.0,"{'valuation_amount': None, 'valuation_currency...","[{'id': 24534, 'round_code': 'unattributed', '...",$6.7M,"[{'funding_round': {'round_code': 'c', 'source...",NaN,[]
16,52cdef7c4bab8bd675297d9c,MeetMoi,15.0,social,"[{'description': None, 'address1': '', 'addres...",2007.0,None,"[{'id': 18, 'round_code': 'a', 'source_url': '...",$5.58M,[],NaN,[]
17,52cdef7c4bab8bd675297d9d,Joost,0.0,games_video,"[{'description': '', 'address1': '100 5th Ave ...",2006.0,None,"[{'id': 19, 'round_code': 'a', 'source_url': '...",$45M,[],NaN,[]
18,52cdef7c4bab8bd675297d9e,CBS,NaN,news,"[{'description': None, 'address1': '', 'addres...",1986.0,"{'valuation_amount': None, 'valuation_currency...",[],$0,"[{'funding_round': {'round_code': 'b', 'source...",NaN,[]
19,52cdef7c4bab8bd675297d9f,Viacom,NaN,web,"[{'description': 'HQ', 'address1': '1515 Broad...",1971.0,"{'valuation_amount': None, 'valuation_currency...",[],$0,"[{'funding_round': {'round_code': 'b', 'source...",NaN,[]
20,52cdef7c4bab8bd675297da0,Babelgum,NaN,games_video,"[{'description': '', 'address1': '', 'address2...",2007.0,None,"[{'id': 17, 'round_code': 'a', 'source_url': '...",$13.2M,[],2013.0,[]
21,52cdef7c4bab8bd675297da1,Plaxo,50.0,web,"[{'description': 'HQ', 'address1': '1050 Enter...",2002.0,None,"[{'id': 20, 'round_code': 'a', 'source_url': '...",$28.3M,[],NaN,[]
22,52cdef7c4bab8bd675297da2,Cisco,63000.0,network_hosting,"[{'description': 'Headquarters', 'address1': '...",1984.0,"{'valuation_amount': None, 'valuation_currency...","[{'id': 2232, 'round_code': 'a', 'source_url':...",$2.5M,"[{'funding_round': {'round_code': 'c', 'source...",NaN,[]
23,52cdef7c4bab8bd675297da3,Yahoo!,13600.0,web,"[{'description': None, 'address1': '701 First ...",1994.0,"{'valuation_amount': None, 'valuation_currency...","[{'id': 24531, 'round_code': 'a', 'source_url'...",$6.8M,"[{'funding_round': {'round_code': 'c', 'source...",NaN,[]
24,52cdef7c4bab8bd675297da4,Powerset,60.0,search,"[{'description': None, 'address1': '475 Branna...",2006.0,None,"[{'id': 22, 'round_code': 'a', 'source_url': '...",$22.5M,[],NaN,[]
25,52cdef7c4bab8bd675297da5,Technorati,35.0,advertising,"[{'description': '', 'address1': '360 Post St....",2002.0,None,"[{'id': 23, 'round_code': 'c', 'source_url': '...",$32.1M,[],NaN,[]
26,52cdef7c4bab8bd675297da9,Mahalo,40.0,web,"[{'description': '', 'address1': '3525 Eastham...",2007.0,None,"[{'id': 323, 'round_code': 'a', 'source_url': ...",$21M,[],NaN,[]
27,52cdef7c4bab8bd675297daa,Sparter,NaN,games_video,"[{'description': None, 'address1': None, 'addr...",2007.0,None,[],$0,[],2008.0,[]
28,52cdef7c4bab8bd675297dab,Kyte,40.0,games_video,"[{'description': None, 'address1': '442 Post S...",2006.0,None,"[{'id': 32, 'round_code': 'a', 'source_url': '...",$23.4M,[],NaN,[]
29,52cdef7c4bab8bd675297dac,Veoh,NaN,games_video,"[{'description': '', 'address1': '10180 Telesi...",2004.0,None,"[{'id': 33, 'round_code': 'b', 'source_url': '...",$69.8M,[],NaN,[]
...,...,...,...,...,...,...,...,...,...,...,...,...
370,52cdef7c4bab8bd675297f3a,MIVA,NaN,advertising,"[{'description': '', 'address1': '41 East 11th...",1999.0,None,[],$0,[],NaN,[]
371,52cdef7c4bab8bd675297f3b,MocoSpace,25.0,games_video,"[{'description': '', 'address1': '', 'address2...",2005.0,None,"[{'id': 497, 'round_code': 'a', 'source_url': ...",$10.5M,[],NaN,[]
372,52cdef7c4bab8bd675297f3c,Adknowledge,300.0,advertising,"[{'description': 'World Headquarters', 'addres...",2004.0,None,"[{'id': 942, 'round_code': 'a', 'source_url': ...",$248M,[],NaN,[]
373,52cdef7c4bab8bd675297f3d,LocaModa,0.0,advertising,"[{'description': 'HQ', 'address1': 'One Broadw...",2007.0,None,"[{'id': 13092, 'round_code': 'a', 'source_url'...",$7.9M,[],NaN,[]
374,52cdef7c4bab8bd675297f3e,airG,180.0,search,"[{'description': '', 'address1': 'Suite 710, 1...",2000.0,None,[],$0,[],NaN,[]
375,52cdef7c4bab8bd675297f3f,YouBeQB,8.0,games_video,"[{'description': None, 'address1': None, 'addr...",2008.0,None,"[{'id': 503, 'round_code': 'a', 'source_url': ...",$0,[],NaN,[]
376,52cdef7c4bab8bd675297f41,RampedMedia,6.0,web,"[{'description': None, 'address1': '1225 Macka...",2006.0,None,"[{'id': 507, 'round_code': 'angel', 'source_ur...",$0,[],2013.0,[]
377,52cdef7c4bab8bd675297f42,ChannelAdvisor,300.0,search,"[{'description': None, 'address1': '2701 Aeria...",2001.0,"{'valuation_amount': 287000000, 'valuation_cur...","[{'id': 508, 'round_code': 'c', 'source_url': ...",$75M,[],NaN,[]
378,52cdef7c4bab8bd675297f43,Yap,NaN,messaging,"[{'description': '', 'address1': '940 Market S...",2006.0,None,"[{'id': 509, 'round_code': 'angel', 'source_ur...",$12M,[],NaN,[]
379,52cdef7c4bab8bd675297f44,Frazr,NaN,web,"[{'description': None, 'address1': None, 'addr...",NaN,None,"[{'id': 510, 'round_code': 'a', 'source_url': ...",$0,[],2013.0,[]
380,52cdef7c4bab8bd675297f45,Tizra,NaN,enterprise,"[{'description': None, 'address1': '9 Catalpa ...",2006.0,None,"[{'id': 511, 'round_code': 'seed', 'source_url...",$850k,[],NaN,[]
381,52cdef7c4bab8bd675297f46,PunchStock,NaN,web,"[{'description': None, 'address1': None, 'addr...",NaN,None,[],$0,[],NaN,[]
382,52cdef7c4bab8bd675297f47,GoChongo,NaN,web,"[{'description': 'HQ', 'address1': '', 'addres...",NaN,None,"[{'id': 513, 'round_code': 'seed', 'source_url...",$175k,[],NaN,[]
383,52cdef7c4bab8bd675297f48,Minglebox,NaN,web,"[{'description': None, 'address1': None, 'addr...",2006.0,None,"[{'id': 514, 'round_code': 'a', 'source_url': ...",$7M,[],NaN,[]
384,52cdef7c4bab8bd675297f49,MyZimu,NaN,web,"[{'description': None, 'address1': None, 'addr...",NaN,None,[],$0,[],NaN,[]
385,52cdef7c4bab8bd675297f4a,TestFreaks,NaN,ecommerce,"[{'description': 'Main office', 'address1': 'O...",2006.0,None,"[{'id': 516, 'round_code': 'a', 'source_url': ...",$5.8M,[],NaN,[]
386,52cdef7c4bab8bd675297f4b,Itiva,NaN,web,"[{'description': None, 'address1': None, 'addr...",NaN,None,"[{'id': 517, 'round_code': 'a', 'source_url': ...",$7M,[],NaN,[]
387,52cdef7c4bab8bd675297f4c,Quattro Wireless,NaN,advertising,"[{'description': None, 'address1': '260 Charle...",2006.0,None,"[{'id': 518, 'round_code': 'a', 'source_url': ...",$28.3M,[],NaN,[]
388,52cdef7c4bab8bd675297f4d,BlogSigs,NaN,web,"[{'description': None, 'address1': None, 'addr...",2007.0,None,[],$0,[],NaN,[]
389,52cdef7c4bab8bd675297f4f,Ripl,NaN,network_hosting,"[{'description': None, 'address1': None, 'addr...",NaN,None,"[{'id': 567, 'round_code': 'b', 'source_url': ...",$6.5M,[],NaN,[]
390,52cdef7c4bab8bd675297f50,BBE,NaN,advertising,"[{'description': '', 'address1': '245 Fifth Av...",2004.0,None,"[{'id': 1373, 'round_code': 'a', 'source_url':...",$10M,[],NaN,[]
391,52cdef7c4bab8bd675297f51,nellymoser,NaN,web,"[{'description': None, 'address1': None, 'addr...",NaN,None,[],$0,[],NaN,[]
392,52cdef7c4bab8bd675297f52,Tacoda,NaN,web,"[{'description': None, 'address1': None, 'addr...",NaN,None,"[{'id': 12332, 'round_code': 'd', 'source_url'...",$19M,[],NaN,[]
393,52cdef7c4bab8bd675297f53,Thumbplay,70.0,music,"[{'description': None, 'address1': '599 Broadw...",2004.0,None,"[{'id': 1839, 'round_code': 'e', 'source_url':...",$41.5M,[],NaN,[]
394,52cdef7c4bab8bd675297f54,Fotolog,40.0,network_hosting,"[{'description': None, 'address1': None, 'addr...",2002.0,None,"[{'id': 523, 'round_code': 'c', 'source_url': ...",$4M,[],NaN,[]
395,52cdef7c4bab8bd675297f56,Sconex,NaN,web,"[{'description': None, 'address1': None, 'addr...",NaN,None,[],$0,[],NaN,[]
396,52cdef7c4bab8bd675297f57,Lycos,NaN,web,"[{'description': 'Headquarters', 'address1': '...",1995.0,None,[],$0,[],NaN,[]
397,52cdef7c4bab8bd675297f58,Xfire,NaN,games_video,"[{'description': 'Xfire Headquarters', 'addres...",2002.0,None,"[{'id': 25802, 'round_code': 'unattributed', '...",$7M,[],NaN,[]
398,52cdef7c4bab8bd675297f59,MyOfferPal,NaN,web,"[{'description': None, 'address1': None, 'addr...",NaN,None,[],$0,[],NaN,[]
399,52cdef7c4bab8bd675297f5a,Alloy,0.0,news,"[{'description': None, 'address1': '', 'addres...",NaN,None,"[{'id': 16415, 'round_code': 'unattributed', '...",$127M,[],NaN,[]

In [192]:
#Get API for exchange rate

url = "https://api.exchangeratesapi.io/latest?base=USD"
res = requests.get(url)
res.json()

{'rates': {'CAD': 1.3055728934,
  'HKD': 7.8004458315,
  'ISK': 126.348640214,
  'PHP': 51.3419527419,
  'DKK': 6.6545697726,
  'HUF': 289.4872938029,
  'CZK': 22.7454302274,
  'GBP': 0.7991529202,
  'RON': 4.2086491306,
  'SEK': 9.4492197949,
  'IDR': 14110.0044583148,
  'INR': 68.5648684797,
  'BRL': 3.8120374498,
  'RUB': 63.7561301828,
  'HRK': 6.5942933571,
  'JPY': 108.6045474811,
  'THB': 30.7748551048,
  'CHF': 0.992153366,
  'EUR': 0.8916629514,
  'MYR': 4.1405260811,
  'BGN': 1.7439144004,
  'TRY': 5.7337494427,
  'CNY': 6.8812304949,
  'NOK': 8.6348640214,
  'NZD': 1.5058403923,
  'ZAR': 14.1607668301,
  'USD': 1.0,
  'MXN': 18.9550601872,
  'SGD': 1.359518502,
  'AUD': 1.4318323674,
  'ILS': 3.5751226037,
  'KRW': 1178.8408381632,
  'PLN': 3.7922425323},
 'base': 'USD',
 'date': '2019-07-08'}

In [194]:
#get currency types


x = []
for i in with_coords2['total_money_raised']:
    y=re.findall("^\D+",i)
    if y not in x:
        x.append(y)
        
print(x)

[['$'], ['â‚¬'], ['Â£'], ['C$'], []]

In [207]:
def dropSpaces(currency):
    return currency.rstrip()
    

with_coords2['total_money_raised'] = with_coords2['total_money_raised'].apply(dropSpaces)

KeyError: 'total_money_raised'

In [ ]:
def coinsAbsoluteValues(currency):
    currency = str(currency)
    if currency.endswith("M"):
        currency= currency.replace("M","")
        currency= float(currency)*1000000
    if currency.endswith("B"):
        currency= currency.replace("B","")
        currency= float(currency)*1000000000
    if currency.endswith("k"):
        currency= currency.replace("k","")
        currency= float(currency)*1000
    return currency

with_coords2['total_money_raised'] = with_coords2['total_money_raised'].apply(coinsAbsoluteValues)

with_coords2.head()

In [203]:
#Choose companies which have raised more than a $1M


with_coords2['total_money_raised']= with_coords2['total_money_raised'].str.replace("M","000000")
with_coords2['total_money_raised']= with_coords2['total_money_raised'].str.replace("B","000000000")
with_coords2['total_money_raised']= with_coords2['total_money_raised'].str.replace("k","000")

KeyError: 'total_money_raised'

In [205]:
def exchangeRate (currency):
    if currency.startswith("â‚¬"): 
        currency = currency.replace("â‚¬","")
        currency = int(currency*res['Rates']['EUR'])
    if currency.startswith("$"): 
        currency = currency.replace("$","") 
        currency = int(currency*res['Rates']['USD'])
    if currency.startswith("Â£"):
        currency = currency.replace("Â£","")
        currency = int(currency*res['Rates']['GPB'])
    if currency.startswith('C$'):
        currency = currency.replace("C$","")
        currency = int(currency*res['Rates']['SEK'])